### ISSUE TITLE
works but....

### ISSUE THREAD

**Issue by boudicca99** [sidoh/ha_gateway#7] opened 2017-04-11 22:42 UTC
getting an error for curl -i -X GET "http://localhost:8000/smartthings/devices"

{"error":true,"type":"SmartAppException","message":"Not Found"

Yet getting an error for curl -i -X GET "http://localhost:8000/smartthings/routines" works fine. can even trigger "routines" to turn on/off a fan.  but cannot get individual devices. 

* Checked Secret and Client ID (I assume routines wouldn't work
* added client through web portal, and added app to phone via smartthings app, select same fan switch, Authorize yet get same error however routines works ?

Its a bit wonky....any ideas. ?

I am EU so https://graph-eu01-euwest1.api.smartthings.com replacing urls for US site.

**Comment by sidoh** [comment] 2017-04-11 23:56
It sounds like it's hitting an endpoint the smartapp doesn't expect. What smartapp code are you using?

**Comment by sidoh** [comment] 2017-04-11 23:58
Assuming [the one](https://gist.github.com/sidoh/da36d2c1099910ef38a6021dc39a61a4) that's in the README?

Is anything interesting showing up in SmartThings live logging?

**Comment by boudicca99** [comment] 2017-04-12 07:15
yes....the one from the readme...will get some logs together this evening. Many Ta's

PS. I will trim down the number of devices to 1. and see if that works also

**Comment by boudicca99** [comment] 2017-04-12 17:50
18:48:12: error physicalgraph.app.exception.SmartAppException: Not Found
 18:48:11: debug Updated with settings: [theSwitches:[Fan]
 18:46:48: error physicalgraph.app.exception.SmartAppException: Not Found
 18:46:33:debug Updated with settings: [theSwitches:[Fan]] 

The fan is just a Smartthings power switch, I removed all the other devices. Still errors. Yet Routines works.....stumped! :(

**Comment by sidoh** [comment] 2017-04-12 18:31
That's pretty weird. So the error is when you're accessing the `/smartthings/devices` route, correct?

I'll poke around a bit later today to see if I can reproduce it.

**Comment by boudicca99** [comment] 2017-04-12 19:15
https://graph-eu01-euwest1.api.smartthings.com/api/smartapps/endpoints is the url for the endpoints

**Comment by sidoh** [comment] 2017-04-12 19:17
I mean the route in ha_gateway. The route that's failing wht the error you posted is `/smartthings/devices`?

I assume it wasn't working with the hardcoded ST API endpoint? It's a little disappointing that they wouldn't route to the appropriate region automatically.

**Comment by boudicca99** [comment] 2017-04-12 21:49
actually I now I check with https://graph.api.smartthings.com/api/smartapps/endpoints and euwest1 in the ha_gateway it does the same.....works for routines but not for devices for both....I'm missing something somewhere....not sure what though

**Comment by sidoh** [comment] 2017-04-13 05:32
Sorry, looks like I made some changes to the app without updating the Gist. :(

Just updated it. Can you give it a try?

**Comment by boudicca99** [comment] 2017-04-13 17:30
Qapla  :)

{"switches":{"0000000-0000-0000-0000-0000000000":{"name":"Fan","status":"off"}},"thermometers":{}}

Yes the Gist it was.....now returns the device. However following your examples

Follwing your example 

curl -X PUT -d'command=toggle' http://localhost:8000/smartthings/devices/00000000-0000-0000-0000-000000000000

Replacing 00000 with the acquired device code..........I get 404 error

 <h2>Sinatra doesn&rsquo;t know this ditty.</h2>
  <img src='http://localhost:8000/__sinatra__/404.png'>
 
What am I missing now ? :) Fun fun.....and thank you again....fantastic.....stuff either way :)

**Comment by sidoh** [comment] 2017-04-13 17:34
Heh, sorry. Same deal here, README is out of date. I added support for pushing sensor data to SmartThings and messed with the routes in the process.

Try PUTing to `/smartthings/switches/:switch` instead:

```
curl -X PUT -d'command=toggle' http://localhost:8000/smartthings/switches/00000000-0000-0000-0000-000000000000
```

**Comment by boudicca99** [comment] 2017-04-13 17:43
Cracked it!!! :) Ta very muchly....grand stuff.  Right...time to think moving my z-wave devices onto smartthings rather than the aeon z-stick....all because the Domoticz install I have, I've moved from an RPI3 to an ASUS TinkerBoard and it doesn't like both a z-stick and a RFXTrx433e running on the same usb bus, now I can run z-wave albeit cloudy z-wave because I have more RF stuff that Z-wave and that means I can free up the RPI3 for more useful things :) Many Ta's Boudyka

**Comment by sidoh** [comment] 2017-04-13 17:50
🎉 !

I updated the README and my blog post to reflect the appropriate routes. Thanks for raising.

I'll close this since it sounds like you got it working, but obviously feel free to re-open if you run into something else.

**Closed as completed by sidoh** 2017-04-13 17:50 UTC
